name: visdrone_detection
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pillow
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip:
    - jsonschema
    - tensorboard
    - tqdm
    - torchmetrics
    - pycocotools
    - ultralytics